### ISSUE TITLE
Have you used this experiment with redux ?

### ISSUE THREAD

**Issue by lejoss** [rafaelquintanilha/experiments#1]
hi, thanks for the example really helped me, have you tried to use this DnD with redux ?

**Comment by rafaelquintanilha** [comment]
Sure, nothing there is library-specific. You can manage the state of your app with Redux with no problem.

**Comment by lejoss** [comment]
i would like to write you back soon, im gonna take your example and add it to my project, then ill try to manage the state with redux somehow, BTW im just a beginner with react.

thanks.

**Comment by lejoss** [comment]
@rafaelquintanilha if i want to use redux for moving items (sorting), action -> reducer, etc..., where should i call the dispatch ? i mean, should i dispatch an action through in drop method ?

**Comment by rafaelquintanilha** [comment]
A good start would be moving the list to your Redux state and transform `pushCard`, `removeCard` and `moveCard` into reducers. Then the `<Card />` component would only dispatch de actions responsible for changing the state.

**Comment by lejoss** [comment]
so i wouldn't need state anymore in App right ?, the store will set the state.

**Comment by lejoss** [comment]
would you be able to sell some hours to help me through the process ?

**Comment by rafaelquintanilha** [comment]
Yes, you're right. The global state will be on your store. I'll be closing the issue as your question was answered, but you can contact me directly at rafaelquintanilha@poli.ufrj.br
